version: '3.8'
services:
  timer_service:
    build: ./timer_service
    ports:
      - "8000:80"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./timer_service:/app

  admin_service:
    restart: on-failure
    container_name: admin_service
    build: admin_service/
    ports:
      - "8001:80"